name: car_rental
description: A new Flutter project.

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version info: version-name + build-number
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase core for initialization
  firebase_core: ^2.30.1

  # Cloud Firestore database
  cloud_firestore: ^4.17.2

  flutter_map : ^2.1.0

  latlog2 : ^0.8.0

  # Cupertino icons for iOS style
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter projects
  flutter_lints: ^5.0.0

flutter:
  # Includes the Material Design icons
  uses-material-design: true

  # Asset directory
  assets:
    - assets/
