// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_-33Il-hOj8y5ujUxn5Bs4G-p7RbOBo',
    appId: '1:185383061622:web:7b3149bc928da993bc3757',
    messagingSenderId: '185383061622',
    projectId: 'chaminduwn-car-rental',
    authDomain: 'chaminduwn-car-rental.firebaseapp.com',
    storageBucket: 'chaminduwn-car-rental.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzfdCaVHmgTZ1Q6exILc4W_4lwNYrzBE0',
    appId: '1:185383061622:android:a1f7881cb6f47e8fbc3757',
    messagingSenderId: '185383061622',
    projectId: 'chaminduwn-car-rental',
    storageBucket: 'chaminduwn-car-rental.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZY3m0w9AqdubAd5AtDRy6qGXNkDOsh8',
    appId: '1:185383061622:ios:2e761e42e9679884bc3757',
    messagingSenderId: '185383061622',
    projectId: 'chaminduwn-car-rental',
    storageBucket: 'chaminduwn-car-rental.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD_-33Il-hOj8y5ujUxn5Bs4G-p7RbOBo',
    appId: '1:185383061622:web:c67da6f3d33e61dbbc3757',
    messagingSenderId: '185383061622',
    projectId: 'chaminduwn-car-rental',
    authDomain: 'chaminduwn-car-rental.firebaseapp.com',
    storageBucket: 'chaminduwn-car-rental.firebasestorage.app',
  );
}
